// <auto-generated />
using EsVideo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsVideo.Migrations
{
    [DbContext(typeof(ApllicatinDbContext))]
    [Migration("20240530125040_AddUserTable2")]
    partial class AddUserTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EsVideo.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tino",
                            Password = "admin1234567",
                            Surname = "Lebonwski",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Name2",
                            Password = "password2",
                            Surname = "Surname2",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Name3",
                            Password = "password3",
                            Surname = "Surname3",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Name4",
                            Password = "password4",
                            Surname = "Surname4",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Name5",
                            Password = "password5",
                            Surname = "Surname5",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Name6",
                            Password = "password6",
                            Surname = "Surname6",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Name7",
                            Password = "password7",
                            Surname = "Surname7",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Name8",
                            Password = "password8",
                            Surname = "Surname8",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Name9",
                            Password = "password9",
                            Surname = "Surname9",
                            Username = "user9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
